### ISSUE TITLE
Downgrade GCC 

### ISSUE THREAD

**Issue by baraaorabi** [vpc-ccg/calib#19]
Calib depends on `GCC v5.2`. This is because earlier versions have not implemented the full `C++11` file stream functions (something about copy constructors is broken in the earlier versions). But if we want Calib to work with bioconda, we should downgrade our `GCC` to `v4.8.5`. This should be relatively an easy fix.

**Comment by corburn** [comment]
@baraaorabi I don't remember where the documentation is citing the the current compiler version, but I know bioconda has long since updated the compilers.

https://gitter.im/bioconda/Lobby?at=5b0cea5bb6eece791dbf06e6
