### ISSUE TITLE
Clustering and error correction for duplex sequencing

### ISSUE THREAD

**Issue by kanika-arora** [vpc-ccg/calib#29]
Can calib call duplex consensus reads? I have data with xGen duplex seq adapters.

**Comment by baraaorabi** [comment]
- Can u describe the structure of the barcode on the forward and backward 
- Consider two reads sequencing two PCR copies of the same molecule, does your library guarantee that they will have the same content (notwithstanding sequencing errors)? Or could they be reverse complements of each other?

**Comment by kanika-arora** [comment]
- We have 3nt UMI tags. Say read-pairs from top molecular strand have R1 (first in pair) starting with AAA and R2 (second in pair) starting with GGG (barcode=AAA-GGG), the barcode of read pairs coming from the bottom molecular strand would have R1 starting with GGG and R2 with AAA (barcode=GGG-AAA). The adapters used are explained here: http://sfvideo.blob.core.windows.net/sitefinity/docs/default-source/flyer/xgen-duplex-seq-adapter.pdf?sfvrsn=9ee0d07_5
- Top R1 should have the same sequence as Bottom R2, and Top R2 should have the same sequence as Bottom R1. Is that what you wanted to know?

**Comment by baraaorabi** [comment]
So if you give this data to Calib, Calib will cluster the top ones alone and the bottom ones alone. Calib was not designed with duplex sequencing design in mind so it does not consider reverse complements when clustering
