### ISSUE TITLE
Using Calib with 4 input fastqs

### ISSUE THREAD

**Issue by snenish03** [vpc-ccg/calib#30]
Hello,

I have 4 fastq files for each sample - Read_R1.fq Read_R2.fq Read_I1.fq and Read_I2.fq
The I1 and I2 files have the barcodes for my paired end reads. Can I use these as input to Calib?

**Comment by baraaorabi** [comment]
Not by default. You will need to first join the left FASTQ files and join the right ones. So something like this should work:
```bash
awk 'FNR==NR{if (NR%4==1){n=$1} if (NR%4==2){s[n]=$0} if (NR%4==0){q[n]=$0}} FNR!=NR {if (NR%4==1){n=$1} if (NR%4==2){$0=s[n]""$0} if (NR%4==0){$0=q[n]""$0} print}' Read_l1.fq Read_R1.fq > Read_Rl1.fq


awk 'FNR==NR{if (NR%4==1){n=$1} if (NR%4==2){s[n]=$0} if (NR%4==0){q[n]=$0}} FNR!=NR {if (NR%4==1){n=$1} if (NR%4==2){$0=s[n]""$0} if (NR%4==0){$0=q[n]""$0} print}' Read_l2.fq Read_R2.fq > Read_Rl2.fq
```

Then you can give Calib the two new files

**Comment by snenish03** [comment]
Got it. Thank you!
