### ISSUE TITLE
sample index and barcode in deduplicated reads

### ISSUE THREAD

**Issue by snenish03** [vpc-ccg/calib#32]
Hello,

I used Calib to deduplicate my paired end reads. 
`calib -f  S1_R1.fastq -r S1_R2.fastq -o S1_Calib. -l1 17 -l2 0`

I have 8 bases index and 9 bases barcode attached to R1 while nothing attached to R2. Now, After running Calib and calib_cons, I noticed that the 17 bases of index+barcode is still attached to my reads. Is there a way to strip this?

Thanks!

**Comment by baraaorabi** [comment]
Calib does not remove barcodes or indices from the reads. This simple awk script should do just that:
```
awk 'NR%2==0{print($0,18)} NR%2==1 {print $0}' final.R1.fastq > final.R1.trimmed.fastq
```

Note: Calib should work find with index+barcode but it might be an overkill. Consider splitting the reads by sample index first, and then running each sample separately with Calib.

**Comment by snenish03** [comment]
Got it, Thank you!
