### ISSUE TITLE
quality scores of consensus sequences

### ISSUE THREAD

**Issue by rmvpaeme** [vpc-ccg/calib#33]
Hi, I'm trying to use calib in combination with UMI VarCal, but apparently calib adjusts the fastq quality score beyond what is used by Illumina (see https://gitlab.com/vincent-sater/umi-varcal/-/issues/12) and is thus not compatible with UMI VarCal. Is this intended? Is it possible to add an option to adjust this to max 41?

**Comment by baraaorabi** [comment]
Ha! I didn't know that. I didn't know Illumina now limits their Phred scores to 40 (according to [this](https://support.illumina.com/help/BaseSpace_OLH_009008/Content/Source/Informatics/BS/QualityScoreEncoding_swBS.htm) at least). I haven't made a decision on whether I should abide by Illumina-specific Phred scores. 

For now, you can run this command to change all `K`'s to `I`'s:

```
awk 'NR%4==0 {gsub("K", "I")} {print}' calib_out.fastq > calib_out.K_to_I.fastq
```
