### ISSUE TITLE
gzip input

### ISSUE THREAD

**Issue by ruolin** [vpc-ccg/calib#35]
I have gzip file as input. However, when I switched on `-g`, the program finished with just a few read processed. I compiled the lastest master, 721830a. 

> No error or minimizer parameters passed. Selecting parameters based on barcode and inferred read length
Inferred read length 149 from sample of 10000 reads
Selected paramters for (mean) barcode length 6 are:
        error_tolerance 1
        kmer_size       8
        minimizer_count 7
        minimizer_threshold     2
Extracting minimizers and barcodes...
Memory before reading FASTQ:
        1MB
Memory right after reading FASTQ:
        1MB
Memory after reserving for read_to_node_vector & node_to_minimizers:
        1MB
Memory after filling barcode_to_node_map:
        1MB
Memory after releasing node_to_read_map:
        1MB
Memory after reserving barcode_to_nodes_vector:
        1MB
Memory after filling barcodes & barcode_to_nodes_vector:
        1MB
Memory after releasing barcode_to_node_map:
        1MB
Read count: 4
Node count: 4
Barcode count: 4
Memory after exiting extract_barcodes_and_minimizers():
        1MB
Clustering...
Adding edges due to barcode barcode similarity
Number of masks is 12
011111111111 is assigned to thread 0
Thread 0 built LSH in: 0
Thread 0 processed LSH in: 0
101111111111 is assigned to thread 0
Thread 0 built LSH in: 0
Thread 0 processed LSH in: 0
110111111111 is assigned to thread 0
Thread 0 built LSH in: 0
Thread 0 processed LSH in: 0
111011111111 is assigned to thread 0
Thread 0 built LSH in: 0
Thread 0 processed LSH in: 0
111101111111 is assigned to thread 0
Thread 0 built LSH in: 0
Thread 0 processed LSH in: 0
111110111111 is assigned to thread 0
Thread 0 built LSH in: 0
Thread 0 processed LSH in: 0
111111011111 is assigned to thread 0
Thread 0 built LSH in: 0
Thread 0 processed LSH in: 0
111111101111 is assigned to thread 0
Thread 0 built LSH in: 0
Thread 0 processed LSH in: 0

**Comment by baraaorabi** [comment]
Is this all the output? Calib prints out `All done! Have a good day` right before existing. 

Also, looking at the output here, I see that Calib can see only 4 reads. Can you share the output of the following commands:

```
zcat in1.fastq.gz | wc -l 
zcat in2.fastq.gz | wc -l 
zcat in1.fastq.gz | head -n20
zcat in2.fastq.gz | head -n20

```

**Comment by ruolin** [comment]
I did see the `Have a good day` message. I thought this is a general gzip issue because it is the same whichever gzip file I used. Here is a small reproducible example. 
[test1.fq.gz](https://github.com/vpc-ccg/calib/files/5395824/test1.fq.gz)
[test2.fq.gz](https://github.com/vpc-ccg/calib/files/5395825/test2.fq.gz)

`calib -f test1.fq.gz -r test2.fq.gz -o test. -g -l 3`

**Comment by ruolin** [comment]
Hello, any updates on this issue?

**Comment by ruolin** [comment]
I figured out it is because the quality string is truncated. Sorry about the wrong report.
