### ISSUE TITLE
barcode at 3' end

### ISSUE THREAD

**Issue by kmoosi** [vpc-ccg/calib#39]
Hi, 

I've just stepped into NGS data analysis and I am not really familiar to it yet but I'm motivated to analyze my data and my research on the internet took me here...
Sequencing gave me single end reads, with my 16N UMI Tag on the 3' end of the read. 
I've cleaned my data so only the 'sequence of interest with the UMI's attached' reads should be left in my input file. 
I'm a little bit confused from the readme. How can I define the postion of my UMI or should I move it in front of the sequence ?
And since I don't have paired end reads, I can copy my dataset without UMI's for r2 input right?

Thanks in advance

**Comment by baraaorabi** [comment]
@kmoosi 
Calib assumes that barcode sequences are at the start of the reads. So yes, you should move the barcode sequence from the end of each read to its beginning. After that, you can feed Calib the same read file to the `-f` and `-r` parameters. Of course, you should also specify the barcode length (which is now at the start of the read) using `-l` parameter.
