### ISSUE TITLE
using -p for reads with umi one one read only

### ISSUE THREAD

**Issue by alexander-e-f-smith** [vpc-ccg/calib#40]
Hi 
If using "-p" in clustering (--ignored-sequence-prefix-length), and having a umi on one read only (eg -l1 10, -l2 0), will the value of -p be ignored on both fastq reads or just the one with > 0 bases specified for the UMI (-l1 in this case).
Thanks

**Comment by baraaorabi** [comment]
It will be ignored on both sides:
https://github.com/vpc-ccg/calib/blob/master/clustering/extract.cc#L155
