### ISSUE TITLE
How do I obtaining the default parameters

### ISSUE THREAD

**Issue by euphowayne78** [vpc-ccg/calib#42]
Dear Baraa,

A quick question. I understand that the parameters for k-mer size, minimizer count, error tolerance and minimizer threshold are set to the defaults that are dependent on read length if I had not set them myself. Is there a way to find out these defaults parameters?

Thanks,
Wee

**Comment by baraaorabi** [comment]
The if-else logic for the default parameters is here:

https://github.com/vpc-ccg/calib/blob/ada2e8edd66c390b43c500eee5b5d3d97ecb86e1/clustering/commandline.cc#L185
