### ISSUE TITLE
Input: Quality sequence needed?

### ISSUE THREAD

**Issue by kmoosi** [vpc-ccg/calib#43]
Hi,
Since FASTQ is the input format I was wondering if I could also use a fake-FASTQ file as my input, where the quality sequence is missing or randomly inserted but the read sequence is real?
So in other words, does Calib sort and cluster the reads also based on quality information or only on sequence similarity?
Thanks for upcoming answers.

**Comment by baraaorabi** [comment]
Yeah you can enter any random quality scores. The clustering is done only using the DNA/RNA sequences. And the final quality scores depends only on the multiple sequence alignment consensus building of the sequences and not on the original quality scores.
