### ISSUE TITLE
Calib run error: Segmentation Fault 11

### ISSUE THREAD

**Issue by kartikchandran** [vpc-ccg/calib#44]
Hi there, 
I'm getting a Segmentation fault 11 error code when trying to run Calib. Please see below.

Thanks for your help!
Kartik

 Kartiks-MBP-2:dms2-subamp-seq-test kartik$ calib -f ./fastqfiles_A33R/appendedWithUMI_s1.CTGATCGT-GCGCATAT.J1230.AHCFMLAFX2.L1-4.1.fastq -r ./fastqfiles_A33R/s1.CTGATCGT-GCGCATAT.J1230.AHCFMLAFX2.L1-4.2.fastq -l 9 -o foo_  
No error or minimizer parameters passed. Selecting parameters based on barcode and inferred read length
Inferred read length 155 from sample of 10000 reads
Selected paramters for (mean) barcode length 9 are:
	error_tolerance	2
	kmer_size	8
	minimizer_count	7
	minimizer_threshold	2
Extracting minimizers and barcodes...
Memory before reading FASTQ:
Segmentation fault: 11

**Comment by kartikchandran** [comment]
Tried to do this. Installed gdb through conda and run it but get another error: 
dyld: Symbol not found: _BC
  Referenced from: /Users/kartik/opt/miniconda3/bin/gdb
  Expected in: /Users/kartik/opt/miniconda3/bin/../lib/libncursesw.6.dylib
 in /Users/kartik/opt/miniconda3/bin/gdb
Abort trap: 6

Sigh. Any suggestions would be welcome. If it's not obvious already, I'm not a power Unix user :p 

Thanks
kc

**Comment by kartikchandran** [comment]
I'll try it.
kc

**Comment by kartikchandran** [comment]
OK, I was able to run LLDB (thanks for the tip) and got the following output

run -f /Users/kartik/ncbi/dms2-subamp-seq-test/testf.fastq -r /Users/kartik/ncbi/dms2-subamp-seq-test/testr.fastq -l 9 -o foo.
Process 87948 launched: '/Users/kartik/Documents/GitHub/calib/calib_dbg' (x86_64)
No error or minimizer parameters passed. Selecting parameters based on barcode and inferred read length
Inferred read length 155 from sample of 10000 reads
Selected paramters for (mean) barcode length 9 are:
	error_tolerance	2
	kmer_size	8
	minimizer_count	7
	minimizer_threshold	2
Extracting minimizers and barcodes...
Memory before reading FASTQ:
Process 87948 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x68)
    frame #0: 0x00007fff67585a5d libsystem_c.dylib`flockfile + 18
libsystem_c.dylib`flockfile:
->  0x7fff67585a5d <+18>: movq   0x68(%rbx), %rdi
    0x7fff67585a61 <+22>: addq   $0x8, %rdi
    0x7fff67585a65 <+26>: callq  0x7fff675cd4d6            ; symbol stub for: pthread_mutex_lock
    0x7fff67585a6a <+31>: callq  0x7fff675cd008            ; symbol stub for: __error
Target 0: (calib_dbg) stopped.

**Comment by baraaorabi** [comment]
Ah, I think I know what's going wrong. The `get_memory_use()` function assumes a Linux operating system process file structure. So it fails on MACOS. Try running with `--silent` option, which should disable calling this function and hopefully should work.

**Comment by kartikchandran** [comment]
Here's the backtrace:

**Comment by baraaorabi** [comment]
Oh I see. I use `get_memory_use()` [here ](https://github.com/vpc-ccg/calib/blob/ada2e8edd66c390b43c500eee5b5d3d97ecb86e1/clustering/cluster.cc#L193) too. You should be able to safely comment out this line, recompile, and run with `--no-sort` option. Let me know if this works. If it does, I'll add it as part of a new version release.

**Comment by kartikchandran** [comment]
I commented out the line. How do I recompile? Sorry, I haven't done this before. 
Thanks

**Comment by baraaorabi** [comment]
Run `make` inside the folder.

**Comment by baraaorabi** [comment]
I created a new release that by default should work with MACOS. Can you give it a try?

**Comment by kartikchandran** [comment]
Sure, will test it out and let you know.
kc

Kartik Chandran, PhD
Professor of Microbiology and Immunology
Harold and Muriel Block Faculty Scholar in Virology
Albert Einstein College of Medicine
http://www.chandranlab.org

Email: ***@***.*** ***@***.***>* (preferred)
CC: Going forward, please use
***@***.*** ***@***.***>*
NOT ***@***.***
***@***.***>*

**Comment by kartikchandran** [comment]
The new version worked! Thanks!

A quick question: the mismatch option (e) applies only to the barcodes and not the reads themselves, right?

Best,
kc
