### ISSUE TITLE
Getting an "ERROR: Something is fishy with read:" error

### ISSUE THREAD

**Issue by kartikchandran** [vpc-ccg/calib#45]
Hi there,

I'm trying to run a pair of R1 and R2 files with 12-bp UMI at the 5' end end of each read. 

calib ran with the following messages but seemed to exit with the above error. 

The reads it lists as "fishy" are the very first read pair in the fastq files. I've attached a sample of R1 and R2 fastq files (each read mate has a 12-bp UMI at the 5' end)
[R1_fastq.txt](https://github.com/vpc-ccg/calib/files/7763393/R1_fastq.txt)
[R2_fastq.txt](https://github.com/vpc-ccg/calib/files/7763394/R2_fastq.txt)
[R1_fastq.txt](https://github.com/vpc-ccg/calib/files/7763395/R1_fastq.txt)
. I did some text processing to move the UMIs but did not edit the quality cigar string. Would this cause the error?

Thank you for your help,
Kartik

calib -f ./final_fastq_processed/A-S_R1_filtered.fastq -r ./final_fastq_processed/A-S_R2_reformatted_filtered.fastq -l1 12 -l2 12 -e 0 -k 4 -m 7 -t 3 -o out_
Extracting minimizers and barcodes...
Read count: 3258645
Node count: 2027186
Barcode count: 1145285
Clustering...
Adding edges due to barcode barcode similarity
Number of masks is 1
111111111111111111111111 is assigned to thread 0
Thread 0 built LSH in: 0
Thread 0 processed LSH in: 0
On thread 0 building all LSH took: 0
On thread 0 processing all LSH took: 0
[R2_fastq.txt](https://github.com/vpc-ccg/calib/files/7763400/R2_fastq.txt)

On thread 0 merging local graph with global graph
On thread 0 merging took 0
Building the graph on 1 thread(s) took 1
Adding edges between nodes of identical barcodes with thread 0
Adding edges due to barcodes similarity took: 1807
Extracting clusters
Extracting clusters took: 68
Outputting clusters
ERROR: Something is fishy with read:
name_1	@M01243:273:000000000-K64MD:1:1101:15987:1337 1:N:0:1
sequence_1	TTCCCAGCCGCAACTTTGTGAGTATGGGTAGTAGACTCCTTGAAGAGCTACTACTACAAGTGCTGGGAAGAGCCAACTCAGGGAAATACAGGAAGAGATCACTCGCCATGAGCAGCAGCTTGTCATT
trash	+
quality_1	AAAABFFFFFBBGGGFFFF5BGFHFEA2EAAFGBGHCF5BFHFBGHGGHHHHHHHHDGEGBFHHGFFH3EGFGHH3BB@@55C>13BF??BF???DB331AF1GFEHBHHBEEEG3?FGFGFECAC2B??GC20F2FHHC2>FG
name_2	@M01243:273:000000000-K64MD:1:1101:15987:1337 2:N:0:1
sequence_2	TGCGGCTGGGAAAATGNCAAGCTGCTGCTCATGGCGAGTGATCTCTTACTGTATTTCCCAGAGTTGGCTCATCCCAGCACTTGTAGGAGTAGCTCTTCAAGGAGTCTACTAACCATACTCACAAAGT
trash	+
quality_2	AA1A#>>1AA1F1BBF11E1BFGE00A0D222D221B122D2AD2F111//1DD11FEFHFHAGBFF0GFAGDD11BG01FFFHHHFD2EA>0GEGDDF2BGF110BBF1GFGBB2BFG?//>/E<C/BG<G0</</B/F<F2<

[R1_fastq.txt](https://github.com/vpc-ccg/calib/files/7763407/R1_fastq.txt)

**Comment by kartikchandran** [comment]
Here is the R2 file
[R2_fastq.txt](https://github.com/vpc-ccg/calib/files/7763410/R2_fastq.txt)

**Comment by baraaorabi** [comment]
I think the quality string is shorter than the sequence string which is illegal FASTQ format. That is probably what is causing the problem

**Comment by kartikchandran** [comment]
Ok, I will fix that and try again. I thought perhaps Calib ignored the
quality string.

kc


Kartik Chandran, PhD
Professor of Microbiology & Immunology
Harold and Muriel Block Faculty Scholar in Virology
Albert Einstein College of Medicine
www.chandranlab.org

**Comment by kartikchandran** [comment]
I fixed the quality string length and everything worked smoothly and very fast, and the output makes sense :) Thank you for all of your efforts in helping me get this up and running!

-kc
